# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('acm_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('representative_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='newsindex',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='newsindex',
        ),
        migrations.RemoveField(
            model_name='newsitemrevision',
            name='newsitem',
        ),
        migrations.RemoveField(
            model_name='newsitemrevision',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewsIndex',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.DeleteModel(
            name='NewsItemRevision',
        ),
    ]
