# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('officer_title', models.CharField(max_length=50)),
                ('officer_picture', models.FileField(blank=True, null=True, upload_to=b'')),
                ('officer_facebook', models.TextField(blank=True, null=True)),
                ('officer_linkedin', models.TextField(blank=True, null=True)),
                ('officer_twitter', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('officer_bio', wagtail.wagtailcore.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
