# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acm_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengepage',
            name='challenge_code',
        ),
    ]
